# Workflow Name
name : First Workflow

# Event at which the workflow to be triggered
on : 
  push:
  workflow_dispatch:

jobs:

  Hello-Job:
  #runner 
    runs-on: ubuntu-latest
    steps:
        - name : Hello World
          run : echo "Hello World"
